CREATE TABLE IF NOT EXISTS pet_page_views (
  pet_id VARCHAR(96) NOT NULL PRIMARY KEY,
  view_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
